---
title: "Assignment 3 Task 3"
author: "Grace Brofman"
date: "2/16/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(tidytext)
library(textdata)
library(pdftools)
library(ggwordcloud)
library(patchwork)
```
I used a magazine I found in the online text archive:https://archive.org/details/texts
specific text: https://archive.org/details/j4g09/page/n15/mode/2up
I found this magazine silly and sexist. The first half is "just for girls", while the second half is "just for boys". The two sides are meant to give each side insight into the other gender. I wanted to see how the sentiments changed (if at all) between the "girls'" side and the "boys'" side.
```{r}
# upload text
mag_text <- pdf_text("Just for Girls and Guys.pdf")

# tidy text
mag_tidy <- data.frame(mag_text) %>% 
  mutate(text_full = str_split(mag_text, pattern = "page_break")) %>%   # breaks at "page_break"
  unnest(text_full) %>% 
  mutate(text_full = str_trim(text_full)) # trims excess whitespace

mag_df <- mag_tidy %>% 
  mutate(page = case_when(
    str_detect(text_full, pattern = "Beginning page") ~ text_full,
    TRUE ~ NA_character_
  )) %>% 
  fill(page) %>% 
  separate(col = page, into = c("pg", "no"), sep = "page ") %>% 
  mutate(page = as.numeric(as.character(no))) # changing page number from character to numberic in new column

```

```{r}
# convert to tokens using unnest_tokens()

mag_tokens <- mag_df %>% 
  unnest_tokens(word, text_full) %>% 
  dplyr::select(-mag_text) %>% 
  filter(!word == "100") %>% 
  filter(!word == "10") %>% 
  filter(!word == "9") %>% 
  filter(!word == "8") %>% 
  filter(!word == "7") %>% 
  filter(!word == "6") %>% 
  filter(!word == "5") %>% 
  filter(!word == "4") %>% 
  filter(!word == "3") %>% 
  filter(!word == "2") %>% 
  filter(!word == "1")  %>% 
  filter(!word == "16") %>% 
  filter(!word == "2010") %>% 
  filter(!word == "2011") %>%
  filter(!word == "25")
  

# word count by page:
mag_wordcount <- mag_tokens %>% 
  count(page, word)

# remove stop words from mag_tokens
mag_nonstop_words <- mag_tokens %>% 
  anti_join(stop_words)

nonstop_counts <- mag_nonstop_words %>% 
  count(page, word)

nonstop_counts

# top 5 words by page
top_5_words <- nonstop_counts %>% 
  group_by(page) %>% 
  arrange(-n) %>% 
  slice(1:5)

ggplot(data = top_5_words,
       aes(x = word, y = n)) +
  geom_col(fill = "blue") +
  facet_wrap(~page, scales = "free") +
  coord_flip()


```
word clouds:
```{r}
# girl-focused pages are 1-8. boy-focused pages are 9-16.
girl_top_50 <- nonstop_counts %>% 
  filter(page == c(1:8)) %>% 
  arrange(-n) %>% 
  slice(1:50)

boy_top_50 <- nonstop_counts %>% 
  filter(page == c(9:16)) %>% 
  arrange(-n) %>% 
  slice(1:50)

girl_cloud <- ggplot(data = girl_top_50,
                     aes(label = word)) +
  geom_text_wordcloud(aes(color = n, size = n)) +
  scale_size_area(max_size = 8) +
  labs(title = "50 most common words in girl-focused pages")

boy_cloud <- ggplot(data = boy_top_50,
                     aes(label = word)) +
  geom_text_wordcloud(aes(color = n, size = n)) +
  scale_size_area(max_size = 8) +
  labs(title = "50 most common words in boy-focused pages")

# put both graphs in one?

girl_cloud
boy_cloud

```

```{r}
# sentiment analysis using AFINN lexicon 
mag_afinn <- mag_nonstop_words %>%  # finding common words beteen mag_nonstop_words and afinn lexicon
  inner_join(get_sentiments("afinn"))

# for each page, how many times does each sentiment score show up?
afinn_counts <- mag_afinn %>% 
  count(page, value)

afinn_means <- mag_afinn %>% 
  group_by(page) %>% 
  summarize(mean_afinn = mean(value))

ggplot(data = afinn_means,
       aes(x = page,
           y = mean_afinn)) +
  geom_col(aes(fill = mean_afinn)) +
  coord_flip()


# girl-targeted pages are 1-8, boy-targeted pages are 9-16. it seems that in general, the boy-targeted pages are associated with a higher positivity than the girl-targeted pages
```

